spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_db
    username: root
    password: root
  cloud:
    config:
      enabled: false
server:
  servlet:
    context-path: /internal
  port: 8282
